import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const api = await readFile(new URL('../src/api/workspace.ts', import.meta.url), 'utf8')
const view = await readFile(new URL('../src/views/WorkspaceOverviewView.vue', import.meta.url), 'utf8')
const directoryView = await readFile(new URL('../src/views/ServiceDirectoryView.vue', import.meta.url), 'utf8')
const router = await readFile(new URL('../src/router/index.ts', import.meta.url), 'utf8')
const topologyView = await readFile(new URL('../src/views/DependencyTopologyView.vue', import.meta.url), 'utf8')
const qualityView = await readFile(new URL('../src/views/ChangeQualityView.vue', import.meta.url), 'utf8')

assert.match(api, /service-graph\/directory/)
assert.match(api, /encodeURIComponent\(workspaceId\)/)
assert.match(api, /X-Workspace-Principal': principal/)
for (const field of ['generation_id', 'repo_id', 'page_size', 'depth', 'node_limit', 'cursor']) {
  assert.match(api, new RegExp(`Object\.entries\(params\).*${field}|${field}`))
}
assert.match(api, /value !== undefined && value !== ''/)
assert.match(view, /fetchWorkspaceServiceGraphDirectory\(workspaceId\.value, principal\.value, requestParams\.value\)/)
assert.match(view, /watch\(\[workspaceId, principal, requestParams\], load, \{ immediate: true \}\)/)
assert.match(view, /to="\/graph"/)
assert.match(view, /to="\/repos"/)
for (const field of ['source_revision', 'sourceRevision', 'revision']) {
  assert.match(view, new RegExp(`['"]${field}['"]`))
}
assert.doesNotMatch(view, /source_revisions|commit|git_sha|latest_revision/)

console.log('P6-A frontend source smoke passed')
assert.match(router, /workspaces\/:workspace_id\/services/)
assert.match(directoryView, /fetchWorkspaceOperationDirectory/)
assert.match(directoryView, /repoFilter/)
assert.match(directoryView, /repo_id: repoFilter/)
assert.match(directoryView, /protocolOptions/)
assert.match(directoryView, /protocolFilter/)
assert.match(directoryView, /v-model\.number="pageSize"/)
assert.match(directoryView, /pageSize/)
assert.match(directoryView, /next_cursor/)
assert.match(directoryView, /cursor = directory\?\.next_cursor/)
assert.match(directoryView, /fetchWorkspaceServiceGraphProviders/)
assert.match(directoryView, /fetchWorkspaceServiceGraphConsumers/)
assert.match(directoryView, /endpointKey/)
assert.match(api, /endpoint_key: endpointKey/)
for (const status of [403, 409, 422]) assert.match(directoryView, new RegExp(`status === ${status}`))
console.log('P6-B frontend source smoke passed')
assert.match(router, /workspaces\/:workspace_id\/topology/)
assert.match(topologyView, /fetchWorkspaceServiceGraphDirectory/)
assert.match(topologyView, /fetchWorkspaceOperationDirectory/)
assert.match(topologyView, /fetchWorkspaceServiceGraphDependencies/)
assert.match(topologyView, /fetchWorkspaceServiceGraphEvidence/)
assert.match(topologyView, /repoFilter/)
assert.match(topologyView, /generationId/)
assert.match(topologyView, /nextAvailable/)
assert.match(topologyView, /visibleIds|visibleEdges/)
assert.match(api, /service-graph\/dependencies/)
assert.match(api, /service-graph\/evidence/)
assert.match(api, /node_id: nodeId/)
for (const status of [403, 409, 422]) assert.match(topologyView, new RegExp(`status === ${status}`))
assert.match(topologyView, /No evidence returned/)
console.log('P6-C frontend source smoke passed')
assert.match(router, /workspaces\/:workspace_id\/quality/)
assert.match(qualityView, /route\.query\.principal/)
assert.match(qualityView, /route\.query\.generation_id/)
assert.match(qualityView, /route\.query\.from_generation/)
assert.match(qualityView, /fetchWorkspaceServiceGraphChanges/)
assert.match(qualityView, /fetchWorkspaceServiceGraphUnresolved/)
assert.match(qualityView, /fetchWorkspaceServiceGraphImpact/)
assert.match(api, /principal, 'changes'/)
assert.match(api, /principal, 'unresolved'/)
assert.match(api, /from_generation_id: fromGenerationId/)
assert.match(qualityView, /changesCursor/)
assert.match(qualityView, /unresolvedCursor/)
assert.match(qualityView, /changedNodeIds\.value\.has\(node\.id\)/)
assert.match(qualityView, /No visible differences were returned/)
assert.match(qualityView, /No visible unresolved records were returned/)
for (const status of [403, 409, 422]) assert.match(qualityView, new RegExp(`status === ${status}`))
console.log('P6-D frontend source smoke passed')
